# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170116_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default=b'+79672473953', max_length=20, verbose_name=b'\xd0\xa2\xd0\xb5\xd0\xbb\xd0\xb5\xd1\x84\xd0\xbe\xd0\xbd'),
        ),
    ]
